#!/bin/bash
# Initialize Discourse configuration with docker-set environment
# variables:
#  $POSTGRES_HOST
#  $POSTGRES_PORT

set -xe

cd /discourse

# production database
sed -i "s/database: discourse_prod/database: postgres/" config/database.yml
sed -i "s/# username: discourse_prod/username: root/" config/database.yml
sed -i "s/# password: itisagooddaytovi/password: postgres/" config/database.yml
sed -i "s/# host: dbhost/host: $POSTGRES_HOST\n  port: $POSTGRES_PORT/" config/database.yml

# test db
sed -i "s/# username: discourse_test/username: root/" config/database.yml
sed -i "s/# password: 123123123123/password: postgres/" config/database.yml
sed -i "s/host: localhost/host: $POSTGRES_HOST\n  port: $POSTGRES_PORT/" config/database.yml

# set site domain
sed -i "s/production.localhost/discourse.example.com/" config/database.yml

# http://stackoverflow.com/a/7529711
sed -i "s/timeout: 5000/timeout: 5000\n  template: template0/" config/database.yml

# Serve public/* from public/assets/* so nginx can directly access the
# assets mount on host.
# http://stackoverflow.com/questions/11021475
echo "Moving public files to assets directory"
rm -rf public/assets/javascripts
mv public/*.* public/javascripts public/assets/
cd public/assets && ln -s /discourse/public/assets assets && cd -

echo "database.yml =>"
cat /discourse/config/database.yml

exec bash -c "$@"
